### ISSUE TITLE
dead link

### ISSUE THREAD

**Issue by jibe-b** [pluto-net/pluto-declaration#4]
In https://github.com/pluto-net/pluto-declaration/blob/master/README.md line 9, link

https://github.com/TylorShin/react-universal-in-serverless/tree/upgrade-packages is dead.

**Comment by TylerShin** [comment]
Hello @jibe-b.
The link is dead because upgrade-packages branch in react-universal-in-serverless is merged to master.
you can follow https://github.com/TylorShin/react-universal-in-serverless then you'll see what you want.

thanks.
